### ISSUE TITLE
Enable .NET Framework 3.5 using Intune Proactive Remediation

### ISSUE THREAD

**Issue by nicowyss** [JayRHa/EndpointAnalyticsRemediationScripts#30]
I'm not exactly the best GitHub user. But from my point of view the following would fit here at most: 
- Enable .NET Framework 3.5
Since certain 3rd party applications need this enabled. Also I have already written a small blog article about this. Maybe it would make sense to include it in the community repo.
https://cloudfil.ch/enable-net-framework-3-5-using-intune-proactive-remediation/

**Comment by andrew-s-taylor** [comment]
Thank you, have added it now :)
